name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git reference to use'
        required: false
        default: 'main'
      sha:
        description: 'Git SHA to use'
        required: false

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      
      - name: Say Hello
        run: echo "Hello World from workflow_dispatch"
